version: "3.9"
name: "app-notes-new"

services:
  server:
    build:
      context: docker/nginx
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - php
  php:
    build:
      context: docker/php
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=docker"
    expose:
      - 9000
    volumes:
      - ./:/var/www/html
      - /tmp/xdebug:/tmp/xdebug
  mysql:
    image: mariadb:11.4
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: notes
      MYSQL_USER: notes
      MYSQL_PASSWORD: notes
      MYSQL_ROOT_PASSWORD: notes
    volumes:
      - database:/var/lib/mysql
  node:
    image: node:18.20.3
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
volumes:
  database: