version: "3.9"
name: "app-notes-new"

services:
  server:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mysql
      - php
  php:
    build:
      context: docker/php
    expose:
      - 9000
    volumes:
      - ./:/var/www/html
  mysql:
    image: mariadb:11.4
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: notes
      MYSQL_USER: notes
      MYSQL_PASSWORD: notes
      MYSQL_ROOT_PASSWORD: notes
    volumes:
      - database:/var/lib/mysql
volumes:
  database: